sudo: required
language: java
services:
- docker
after_success:
- docker build -t se_methods .
- docker run se_methods
before_install:
- openssl aes-256-cbc -K $encrypted_ccd611b0e41a_key -iv $encrypted_ccd611b0e41a_iv
  -in client-secret.json.enc -out client-secret.json -d
