language: java

sudo: false

addons:
  hosts:
  - db

env:
  global:
  # Ensure Google Cloud SDK doesn't prompt for installing.
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

services:
- docker

install:
# Build database image.
- docker build -t database src/db/.
# Run the database image.
- docker run --rm -d -e MYSQL_ROOT_PASSWORD=password -p 33060:3306 database
# Build and install the application.
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
# Clean any files.
- mvn clean

# Job stages
jobs:
  include:
  - stage: unit tests
    install: skip
    jdk: oraclejdk11
    script: mvn test -Dtest=SEMethodsSet088103G1CW.Tests
  - stage: integration tests
    jdk: oraclejdk11
    script: mvn test -Dtest=SEMethodsSet088103G1CW.IntegrationTest
  - stage: GitHub Release
    install: skip
    jdk: oraclejdk11
    script:
    - echo "Deploying to GitHub releases"
    - mvn package -DskipTests=true -Dmaven.javadoc.skip=true
    before_deploy:
    # Set our Git user name and email.
    - git config --local user.name "Syudo"
    - git config --local user.email "natsu.eichiro@gmail.com"
    # Create unique tag for the commit.
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y-%m-%d')-$(git log --format=%h -1)}
    # Tag the commit.
    - git tag $TRAVIS_TAG
    deploy:
      provider: releases
      # Token saved on Travis.
      api_key: "$GITHUB_OAUTH_TOKEN"
      # File to add to the release.
      file: "SEMethods088103G1CW.jar"
      skip_cleanup: true
  - stage: Google Cloud Deploy
    install: skip
    jdk: oraclejdk11
    before_script:
    # Check if Google Cloud SDK is installed.
    - if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash
        > /dev/null; fi
    - source $HOME/google-cloud-sdk/path.bash.inc
    # Install Kubernetes control to manage containers
    - gcloud components install kubectl
    - gcloud version
    # Login to our Google Cloud Account using credentials file
    - gcloud auth activate-service-account --key-file client-secret.json
    script:
    # Set the project we will work in.
    - gcloud config set project semethodsset08103g1
    # Set the zone to work in.
    - gcloud config set compute/zone europe-west2-b
    # Assign project ID to a variable to make life easier
    - export PROJECT_ID="$(gcloud config get-value project -q)"
    # Authenticate against Google's Docker image manager.
    - gcloud auth configure-docker
    # Build the database image.
    - docker build -t gcr.io/${PROJECT_ID}/src/db src/db/.
    # Push the database image.
    - docker push gcr.io/${PROJECT_ID}/src/db
    # Create a container cluster.  We only need one node.
    - gcloud container clusters create world-cluster --num-nodes=1
    # Tell kubernetes to run the built database image, opening port 3306
    - kubectl run world --image=gcr.io/${PROJECT_ID}/src/db --port 3306
    # Expose the cluster to the Internet, mapping external port 3306 to internal port 3306.
    - kubectl expose deployment world --port=3306 --target-port=3306 --type=LoadBalancer

stages:
- unit tests
- integration tests
- name: GitHub Release
  if: branch = master
- name: Google Cloud Deploy
  if: branch = master

after_success:
# Push code coverage data to codecov.
- bash <(curl -s https://codecov.io/bash)

before_install:
# Decrypts the credentials file.
# The keyname will be different for your project.
- openssl aes-256-cbc -K $encrypted_ccd611b0e41a_key -iv $encrypted_ccd611b0e41a_iv
  -in client-secret.json.enc -out client-secret.json -d
