version: '3'
services:
  app:
    build: .

  db:
    build: src/db/.
    command: ['--default-authentication-plugin=mysql_native_password','--character-set-server=latin1','--collation-server=latin1_swedish_ci']
    restart: always