@startuml

actor HR as "Population Information Worker"

rectangle Database

rectangle "World System" {
    usecase UC4 as "Region Report"

    usecase UCa as "Print Region Report"

    HR - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml